### ISSUE TITLE
IOI 버그 리포팅

### ISSUE THREAD

**Issue by backlo** [woowahan-crews/miniprojects-2019#143]
1. 로그인 후 api/users/loggedin으로 접속하면 정보가 다 나와요 !
http://13.209.76.240:8080/api/users/loggedin

2. 게시글 쓸때 아무것도 안쓰면 404 에러 떠요

3. 게시물로 이동했을 때 사진 뒤에 인스타 모양이 나와요

4. search에 값을 입력하면 콘솔에 값이 자꾸 찍혀요

5. 동영상 등록이 안돼요

6. 댓글에서 이름 클릭하면 메인페이지로 이동해요.

7. 댓글에 계속 Enter 치면 계속 댓글이 생겨요

8. 댓글에 스크립트 입력하면 그대로 나와요.

9. 게시글 길게 쓰면 에러가 터져요.

10. 회원 가입 할 때 비밀 번호를 어떤 식으로 정할 지 안알려 줘서 알려주면 좋겠습니다.

11. 사진을 등록할 때 handlebars 가 not defined라고 떠요.

12. 사진 수정을 할 수 있었으면 좋겠습니다.

13. 이름을 한글도 쓸 수 있게 지원 해주세요.

14. 회원 수정 버튼에  mouse over 넣어주세요.

15. 앱 다운로드가 안돼요......

16. 북마크 버튼을 누르면 메인 화면으로 와요.

17. 게시물 조회 페이지 에서 댓글이 안보여요.

18. 알람이 가면 console 에 계속 메세지 가 나와요.

19. 사진을 올리면 사진에 대한 정보가 console 창에 많이 떠요.

20. #땡땡!! 이렇게 치면 #땡땡 으로 나오고 뒤에 특수문자가 안 나와요.

21. 댓글에 해쉬 태그 안돼요.

**Comment by yunheehyeon** [comment]
15 > 멋
16 > 지원하지 않는 기능 (지워야 하나?) 
17 > 규동이 수정
18 > 흠... 빌드할 때 콘솔 로그를 지우는 방법이 있을 거 같은데? (외부 라이브러리에서 콘솔 로그를 찍고 있음)
19 > 18번과 같은 문제, 일단 주석 처리함
20 > 인스타 확인 결과 이모지는 되는데 ! 는 안됨
21 > 더 이상 추가 기능 업뎃 없음
