### ISSUE TITLE
브라운 코드리뷰 반영

### ISSUE THREAD

**Issue by green4469** [woowahan-crews/miniprojects-2019#21]
- [x] 빌드/배포시 테스트 수행되는지 확인
- [x] ArticleService 의 save 메서드에서 파일 관련 로직 분리
- [x] 테스트명에서 카멜케이스(e.g., moominIsMoomin)와 스네이크케이스(e.g., moomin_is_moomin) 혼용하지 말기
- [x] ArticleControllerTest 에 Article 생성 테스트 작성 (MultiPartFile 문제)
- [x] User.java 와 Article.java 필드 간격 일치
- [x] 테스트코드에서 ObjectMapper를 사용하지 않고 expectBody로 바로 객체를 받아오기
- [x] ArticleService 와 ControllerService 메서드 네이밍 일치

**Comment by seonghun127** [comment]
1. 데미테르 법칙
2. Assembler 사용
