### ISSUE TITLE
JPA 원시타입 사용 문제

### ISSUE THREAD

**Issue by seonghun127** [woowahan-crews/miniprojects-2019#5]
```
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String title;

    private String coverUrl;

    private String contents;
```
Entity에서 각 칼럼에 해당하는 필드의 타입을 원시 타입으로 할 것이냐, wrapper로 할 것이냐

**Comment by green4469** [comment]
이바 멋있어

**Comment by green4469** [comment]
long vs Long

https://stackoverflow.com/questions/3535791/primitive-or-wrapper-for-hibernate-primary-keys/3537407#3537407

위 링크를 확인해보면, 원시타입은 null 값이 원천적으로 들어갈 수가 없기 때문에 default value와 null을 구분할 수가 없게 된다. 따라서 원시 타입은 사용하지 말고 Wrapper 클래스를 사용하라.

**Comment by green4469** [comment]
이슈 닫겠습니다~
